apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: nitinklr23/payments
          env:
            - name: KAFKA_CLIENT_ID
              value: ticket-management
            - name: KAFKA_BROKER_SERVER
              value: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
            - name: KAFKA_USER_NAME
              value: TZY72EO6P7QZ6GGP
            - name: KAFKA_PASSWORD
              value: iECC14jGPUgiA6dm3t4s4KS+yqWyXFXI8bit/88OjZNc3SzdJ0Qg3IF1CWZEGhdj
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
