name: tests-expiration

on:
  pull_request
    path:
      - 'expiration/**'
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd expiration && npm install && npm run test:ci
